# Number of scanning jobs to run concurrently
max_concurrent_jobs: 1
# NSFW detection threshold (0.0 to 1.0, default 0.5)
nsfw_threshold: 0.65
# Room to report images to (leave blank for no reporting)
# e.g. '!room:myserver.local'
report_to_room: null
# List of Matrix servers to include in matrix.to URLs
via_servers:
  - matrix.org
# True/false actions to perform based on results
actions:
  ignore_sfw: true
  redact_nsfw: false
  direct_reply: false
  post_errors: false
