# All actions are true/false, except report_to_room
# which should be the room ID in single quotes of the
# desired room, e.g. '!room:myserver.local'
max_concurrent_jobs: 1
via_servers:
    - matrix.org
actions:
    ignore_sfw: true
    redact_nsfw: false
    direct_reply: false
    report_to_room: ""
