# Number of scanning jobs to run concurrently
max_concurrent_jobs: 1
# NSFW detection threshold (0.0 to 1.0, default 0.5)
nsfw_threshold: 0.5
# List of Matrix servers to include in matrix.to URLs
via_servers:
  - matrix.org
# Actions are true/false, except report_to_room which
# should be a room ID in single quotes,
# e.g. '!room:myserver.local'
actions:
  ignore_sfw: true
  redact_nsfw: false
  direct_reply: false
  report_to_room: ""
