# Maximum concurrent image processing jobs allowed
max_concurrent_jobs: 1
# Via servers to use in matrix.to URLs
via_servers:
    - matrix.org
# Actions to take when bot is triggered - all are true/false,
# except report_to_room which should be set to room ID/alias
# (in quotes) of the desired room, e.g. '#mods:myserver.local'
actions:
    ignore_sfw: true
    direct_reply: false
    report_to_room: false
