name: Build and Test

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Prepare uv
        uses: astral-sh/setup-uv@v5

      - name: Run tests and build plugin
        run: |
          # Install dependencies
          uv sync --dev
          # Lint with ruff
          echo "## Ruff Check Results" >> $GITHUB_STEP_SUMMARY
          uv run ruff check . --output-format=github >> $GITHUB_STEP_SUMMARY
          echo "## Ruff Format Results" >> $GITHUB_STEP_SUMMARY
          uv run ruff format --check --diff . >> $GITHUB_STEP_SUMMARY
          # Run tests
          echo "## Test Results" >> $GITHUB_STEP_SUMMARY
          uv run pytest --verbose >> $GITHUB_STEP_SUMMARY
          # Build plugin
          uv run mbc build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nsfwbot-plugin
          path: "*.mbp"
          compression-level: 0
